background = "#101412"
border = "#2d4637"
terminal_border = "#4682b4"
selection = "#1e3228"
session_selection = "#3c3c3c"
title = "#39ff14"
text = "#b4ffb4"
dimmed = "#50785a"
hint = "#64a078"
running = "#00ffb4"
waiting = "#ffb43c"
idle = "#3c6446"
error = "#ff6450"
terminal_active = "#82aaff"
group = "#64dca0"
search = "#b4ffc8"
accent = "#39ff14"
diff_add = "#00ff00"
diff_delete = "#ff0000"
diff_modified = "#ffff00"
diff_context = "#808080"
diff_header = "#00ffff"
help_key = "#ffff00"
branch = "#00ffff"
sandbox = "#ff00ff"
worktree_managed = "#00ff00"
worktree_manual = "#ffff00"
